-- Migration: Create 'books' table with metadata and text content

-- Create the 'books' table
create table public.books (
    id bigint generated by default as identity primary key, -- Unique identifier for each book
    gutenberg_id bigint not null unique,                   -- Unique Project Gutenberg ID
    metadata jsonb default '{}'::jsonb,                    -- JSONB column to store metadata
    content text,                                          -- Column to store the book's text content
    created_at timestamp with time zone default now() not null
);

-- Enable Row-Level Security (RLS) on the 'books' table
alter table public.books enable row level security;

-- Grant necessary privileges to roles
grant select, insert, update, delete on table public.books to anon;
grant select, insert, update, delete on table public.books to authenticated;
grant all privileges on table public.books to service_role;

CREATE UNIQUE INDEX gutenberg_id_unique_idx ON public.books USING btree (gutenberg_id);


-- Create policies for role-based access control

-- Policy: Allow all users to read data
create policy "Allow read access for all users"
on public.books
as permissive
for select
to public
using (true);

-- Policy: Allow all users to insert data
create policy "Allow insert for all users"
on public.books
as permissive
for insert
to public
with check (true);
